### ISSUE TITLE
Case mounting tabs and CT numbers

### ISSUE THREAD

**Issue by presslab-us** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#13]
I wanted to use the Orbit 57095 Timer Cabinet to house the energy meter: https://www.orbitonline.com/product/gray-outdoor-timer-cabinet/

The provided 3D printed case didn't really have mounting like I wanted it, so I have modified the STL files to add mounting tabs that line up with existing holes in that cabinet.  This cabinet will fit up to the 24-input (3 addon board) energy meter.

The second change was adding numbers to the sides of the case so it can be quickly seen what the CT input number is.

Ideally these changes would be in the source CAD file, and not just the STLs, so if this improvement is desired that would be the proper place to make these changes.  I didn't see the CAD files available on GitHub.

Here's the OpenSCAD remix and STLs for a 6-input and 24-input version: [case_mod.zip](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/files/4672481/case_mod.zip)

![IMG_20200523_164225](https://user-images.githubusercontent.com/5122115/82740244-fd221f00-9d14-11ea-8624-345095ca7b70.jpg)
![IMG_20200523_164322](https://user-images.githubusercontent.com/5122115/82740247-ff847900-9d14-11ea-9cab-0cc768a4d441.jpg)

**Comment by CircuitSetup** [comment]
Thanks for sharing your case! I'll have the tabs in the master. Also, very clean install!
