### ISSUE TITLE
Dead link on github page and lowest power consumption that can be measured

### ISSUE THREAD

**Issue by bartgrefte** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#44]
There's a dead link on https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter , ctrl+f for "here for some more advanced configurations". If I had to guess, I think it should be https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/tree/master/Software/ESPHome

In addition to that, I'm curious about something, what's the lowest power consumption a setup using the 6-Channel ESP32 Energy Meter can measure? Don't see that in the specs, or I overlooked it.

**Comment by CircuitSetup** [comment]
Thanks, that link is fixed. 

The lowest the meter can register depends on the accuracy of the CT and if it is calibrated or not. Generally, with the YHDC CTs, the accuracy is going to be within 2% (1% CT accuracy, 1% meter burden resistor accuracy) for amperage. Then factoring in the accuracy of the voltage measurement (the newest meters have a 0.5% resistors for the voltage dividers), and about 1% for the Jameco Transformers.

So, it can go down pretty low to about 1-2 watts.

**Comment by bartgrefte** [comment]
As low as 1-2 watts is perfect, thanks for the info :)
