### ISSUE TITLE
Monitoring a 400 A service (2x 200 A panels)

### ISSUE THREAD

**Issue by kspearrin** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#89]
I have 1x 6 channel board and am getting ready to connect things. My goal is to monitor my whole home energy consumption via ESPHome (config taken from this repo) and Home Assistant. My home (located in US) has a 400 A service from the street which is divided at the meter into 2x 200 A panels that are in my garage next to each other. The various circuits in my house are divided up between each of these 2 panels.

Can I monitor this correctly with a single 6 channel board? After reading through the docs, my understanding is that I need:

- CT1 - Panel 1 Main 240V red
- CT2 - Panel 1 Main 240V black (inverted clamp?)
- CT3 - Extra for some 120V circuit on panel 1
- CT4 - Panel 2 Main 240V red
- CT5 - Panel 2 Main 240V black (inverted clamp?)
- CT6 - Extra for some 120V circuit on panel 2

I would then need to somehow combine the readings from CT1, CT2, CT4, and CT5 to get the "whole home" reading.

Does this sound correct?

One part in the docs that confused me a bit was about measuring a second voltage. Does this apply in my situation with having two panels? I would think the voltages are the same between the two. My current plan is to power the board from a single wall outlet coming one of the panels (could be either). 

Thanks. Looking forward to getting this up and running soon.

**Comment by CircuitSetup** [comment]
Yes, what you describe is exactly how you should set things up with the 6 channel meter, assuming that the mains wires coming into each side of the 2 panels are red and black. 

For adding everything together, see [this template in this example](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/blob/master/Software/ESPHome/6chan_energy_meter_house_solar_ha_kwh.yaml#L151). Then you can show everything in the Energy panel of HA with the [total_daily_energy sensor.](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/blob/master/Software/ESPHome/6chan_energy_meter_house_solar_ha_kwh.yaml#L178)

You shouldn't need to worry about measuring more than one voltage unless you suspect that one side of a panel is unbalanced, and is experiencing voltage sag when something large is switched on. The corresponding side of each of your 2 panels are likely in phase with each other, which are 120V each.

**Comment by CircuitSetup** [comment]
Yes, you can do that. You would set it up similar to the example linked above.

**Comment by CircuitSetup** [comment]
It is 65A per CT. The likelihood that you use a sustained 130A (assuming your large loads are 240V dual pole circuits) on a single panel is low, but possible, especially if you have a very large house to cool, or have farm equipment (some customers have had these exact situations).

The point is, I wouldn't half the power calibration values unless you have to. The readings at lower power values will not be as accurate and you would have to calibrate more precisely.
